module.exports.utils = {
  LANDING_SCREEN_ROUTE: "/landing",
  LOGIN_SCREEN_ROUTE: "/auth/login",
  REGISTER_SCREEN_ROUTE: "/auth/register",
  HOME_SCREEN_ROUTE: "/",
  CONTACT_US_SCREEN_ROUTE: "/settings/contactUs",
  ABOUT_US_SCREEN_ROUTE: "/settings/aboutUs",
  PRIVACY_POLICY_SCREEN_ROUTE: "/settings/privacyPolicy",
  TERMS_OF_USE_SCREEN_ROUTE: "/settings/termsOfUse",
  FAQ_SCREEN_ROUTE: "/settings/faq",
  PRODUCTS_BY_CATEGORY_SCREEN_ROUTE: "/products/productsByCategory",
  PRODUCTS_BY_BRAND_SCREEN_ROUTE: "/products/productsByBrand",
  CART_SCREEN_ROUTE: "/myPortfolio/cart",
  WISHLIST_SCREEN_ROUTE: "/myPortfolio/wishlist",
  MY_PROFILE_SCREEN_ROUTE: "/myPortfolio/myProfile",
  ORDERS_SCREEN_ROUTE: "/myPortfolio/orders",
  NOTIFICATIONS_SCREEN_ROUTE: "/settings/notifications",
  SUPPORT_SCREEN_ROUTE: "/settings/support",
  CHECKOUT_SCREEN_ROUTE: "/checkout",
  LOGGED_OUT_CONTACT_US_SCREEN_ROUTE: '/auth/settings/contactUs',
  LOGGED_OUT_ABOUT_US_SCREEN_ROUTE: '/auth/settings/aboutUs',
  LOGGED_OUT_PRIVACY_POLICY_SCREEN_ROUTE: '/auth/settings/privacyPolicy',
  LOGGED_OUT_TERMS_OF_USE_SCREEN_ROUTE: '/auth/settings/termsOfUse',
  LOGGED_OUT_FAQ_SCREEN_ROUTE: '/auth/settings/faq',
};
