module.exports.utils = {
  LANDING_SCREEN_ROUTE: "/landing",
  LOGIN_SCREEN_ROUTE: "/auth/login",
  REGISTER_SCREEN_ROUTE: "/auth/register",
  HOME_SCREEN_ROUTE: "/",
  CONTACT_US_SCREEN_ROUTE: "/contactUs",
  ABOUT_US_SCREEN_ROUTE: "/aboutUs",
  PRIVACY_POLICY_SCREEN_ROUTE: "/privacyPolicy",
  TERMS_OF_USE_SCREEN_ROUTE: "/termsOfUse",
  FAQ_SCREEN_ROUTE: "/faq",
  PRODUCTS_BY_CATEGORY_SCREEN_ROUTE: "/productsByCategory",
  PRODUCTS_BY_BRAND_SCREEN_ROUTE: "/productsByBrand",
  CART_SCREEN_ROUTE: "/cart",
  WISHLIST_SCREEN_ROUTE: "/wishlist",
  MY_PROFILE_SCREEN_ROUTE: "/myProfile",
  ORDERS_SCREEN_ROUTE: "/orders",
  NOTIFICATIONS_SCREEN_ROUTE: "/notifications",
  SUPPORT_SCREEN_ROUTE: "/support",
};
