module.exports.utils = {
  ADMIN_DEPARTMENT_ID: "e81dc361-5975-4c30-99f6-20d3dab6fc53",
  ACTIVE_EMPLOYEE_STATUS_ID: "6240de93-e947-4625-a414-2ce82075f8dd",
  APP_TYPE_CLIENT: "client",
  APP_TYPE_ADMIN: "admin",
  APP_TYPE_POSTMAN: "postman",
  COMPANY_HQ_ADDR: {
    NAME: "VC Store, Inc.",
    ADDRESS_1: "Suite-901/902, Floor-9th, Unitech Cyber Park, Tower B, Plot-27",
    ADDRESS_2: "Sector-1, IMT Manesar",
    COUNTRY: "India",
    STATE: "Haryana",
    CITY: "Gurugram",
    PINCODE: "122051",
    PHONE: "+(759) 234-8244",
  },
  COMPANY_EMAIL: "support@vcstore.com",
  PRODUCTS_TAX_PERCENT: 18,
  DEFAULT_ACCOUNT_NUMBER: "6000000000000016",
  BANK_ACCOUNT_FOR_CASH_DEPOSIT: {
    accountName: "Cash deposit account",
    bankName: "Cash deposit bank",
    accountNumber: "9000000000000001",
  },
  rupeeSymbol: "₹",
  ENUMS: {
    TOPBAR_MENU: "topbar_menu",
    TOPBAR_AVATAR_MENU: "topbar_avatar_menu",
    HOME_CATEGORY_SIDE_MENU: "home_category_side_menu",
    HOME_CATEGORY_SCREEN_ITEM: "home_category_screen_item",
    HOME_BRAND_SCREEN_ITEM: "home_brand_screen_item",
    FOOTER_LOGGEDIN_QUICK_LINK_SECTION: "footer_loggedin_quick_link_section",
    FOOTER_LANDING_QUICK_LINK_SECTION: "footer_landing_quick_link_section",
    FOOTER_LOGGEDIN_ACCOUNT_SECTION: "footer_loggedin_account_section",
  },
};
